language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t canonglass00/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true canonglass00/docker-react npm run test